name: 张玉洁的组件-59
description: 描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十描述很长一二三四五六七八九十
keywords: 
  - 张玉洁的标签
  - network

license: aaaaa                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

logo: https://zyj666.oss-cn-hangzhou.aliyuncs.com/timg%20%281%29.jpg
homepage: 
source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
